server {
    listen 80;
    server_name _;
    default_type text/html;

    location /file1 {
        alias /var/www/html/index1.html;
    }

    location /file2 {
        alias /var/www/html/index2.html;
    }
    location /file3 {
        alias /var/www/html/index3.html;
    }
}
}
